// ============================================================ 6. Distribution
function vDist() {
  const R = filtered(), key = oracleKey(); const G = graded(R, key); if (!G.length) return `<h2>Distribution</h2>` + empty("No graded runs under this oracle in the filter.");
  let h = `<h2>Non-determinism is statistics</h2><p class="claim">X<sub>ij</sub> ~ Bernoulli(p<sub>i</sub>). One run estimates p with n = 1. The interval tells you what one run is worth; pass@k and pass^k are two different questions asked of the same repeats.</p>`;
  const tt = taskTable(R, key), tasks = Object.keys(tt), maxn = Math.max(...tasks.map(t => tt[t].n));
  h += `<h3><span class="n">1</span> Per task</h3><div class="tbl"><table><tr><th>task</th><th class="num">n</th><th class="num">c</th><th class="num">p̂</th><th class="num">Wilson 95%</th><th class="num">Wald 95%</th>${[2, 3, 5, 10].filter(k => k <= maxn).map(k => `<th class="num">pass@${k}</th><th class="num">pass^${k}</th>`).join("")}<th>probe</th></tr>`;
  tasks.slice(0, 60).forEach(t => { const v = tt[t], w = wilson(v.c, v.n), wd = wald(v.c, v.n); h += `<tr><td><b>${esc(t)}</b></td><td class="num">${v.n}</td><td class="num">${v.c}</td><td class="num">${fmt(v.p)}</td><td class="num">${ciText(w[0], w[1])}</td><td class="num">${ciText(wd[0], wd[1])}</td>${[2, 3, 5, 10].filter(k => k <= maxn).map(k => `<td class="num">${k <= v.n ? fmt(passAtK(v.c, v.n, k)) : ""}</td><td class="num">${k <= v.n ? fmt(passPowK(v.c, v.n, k)) : ""}</td>`).join("")}<td class="small">${esc((B.tasks[t] || {}).probe || "")}</td></tr>`; });
  h += `</table></div><p class="small">Wald collapses to a point at p̂ = 0 or 1; Wilson does not. That is the interval that belongs in a paper.${tasks.length > 60 ? ` First 60 of ${tasks.length} tasks.` : ""}</p>`;
  const hids = uniq(R.map(r => r.harness_id)).slice(0, 8); const ks = Array.from({ length: Math.min(maxn, 20) }, (_, i) => i + 1);
  const sAt = [], sPow = [];
  hids.forEach((hid, i) => { const rs = R.filter(r => r.harness_id === hid); const t2 = taskTable(rs, key); const ts2 = Object.keys(t2); if (!ts2.length) return; const n2 = Math.min(...ts2.map(t => t2[t].n)); const kk = ks.filter(k => k <= n2); if (!kk.length) return; sAt.push({ name: hid, color: SERIES[i], points: kk.map(k => [k, mean(ts2.map(t => passAtK(t2[t].c, t2[t].n, k)))]) }); sPow.push({ name: hid, color: SERIES[i], points: kk.map(k => [k, mean(ts2.map(t => passPowK(t2[t].c, t2[t].n, k)))]) }); });
  if (sAt.length) h += `<h3><span class="n">2</span> pass@k rises, pass^k falls</h3><div class="row"><div class="col">${svgLines(sAt, { xlabel: "k", ymax: 1, xticks: ks })}<div class="small">pass@k: at least one of k runs passes (best case, lenient)</div></div><div class="col">${svgLines(sPow, { xlabel: "k", ymax: 1, xticks: ks })}<div class="small">pass^k: all k runs pass (consistency, what a user experiences)</div></div></div>`;
  // bootstrap distribution + drift
  const [lo, hi, boots] = bootstrapCI(tasks.map(t => tt[t].p), 2000, 7); const byRep = Array.from(by(G, r => r.repeat_index).entries()).sort((a, b) => a[0] - b[0]);
  h += `<h3><span class="n">3</span> The interval, drawn, and a drift check</h3><div class="row"><div class="col narrow"><h4>Task-bootstrap distribution of pass@1</h4>${svgHist(boots, { lo: 0, hi: 1, bins: 25, d: 2, mark: mean(tasks.map(t => tt[t].p)), w: 360, h: 140 })}<div class="small">2,000 resamples of the ${tasks.length} task means; 95% ${ciText(lo, hi)}. The red line is the point estimate.</div></div><div class="col narrow"><h4>Pass rate by repeat index</h4>${svgLines([{ name: "pass rate", color: "#3B6FD9", points: byRep.map(([k, v]) => [k, passRate(v, key)]), band: byRep.map(([k, v]) => { const g = graded(v, key); const w = wilson(g.filter(r => r[key]).length, g.length); return [k, w[0], w[1]]; }) }], { xlabel: "repeat index", ymax: 1, w: 380, h: 200, xticks: byRep.map(([k]) => k), hline: passRate(G, key) })}<div class="small">If the API drifted or the sandbox leaked state between repeats, this is where it shows. Flat around the dashed mean is what you want.</div></div>`;
  const hAll = uniq(R.map(r => r.harness_id)), mAll = uniq(R.map(r => r.model));
  h += `<div class="col"><h4>Flip map (c/n per task and cell)</h4><div class="tbl"><table><tr><th>task</th>${mAll.flatMap(m => hAll.map(hid => `<th>${esc(m)}<br>${esc(hid)}</th>`)).join("")}</tr>${tasks.slice(0, 40).map(t => `<tr><td><b>${esc(t)}</b></td>${mAll.flatMap(m => hAll.map(hid => { const rs = graded(R.filter(r => r.task_id === t && r.harness_id === hid && r.model === m), key); if (!rs.length) return `<td class="small">—</td>`; const c = rs.filter(r => r[key]).length, n = rs.length; const bg = c === n ? "var(--ok-bg)" : (c === 0 ? "var(--bad-bg)" : "var(--warn-bg)"); return `<td style="background:${bg};text-align:center">${c}/${n}</td>`; })).join("")}</tr>`).join("")}</table></div><div class="legend"><span><i style="background:var(--ok-bg)"></i>always passes</span><span><i style="background:var(--bad-bg)"></i>never passes</span><span><i style="background:var(--warn-bg)"></i>mixed: the cell has a distribution, not a value</span></div></div></div>`;
  h += `<h3><span class="n">4</span> Path diversity within a cell</h3><div class="tbl"><table><tr><th>cell × task</th><th class="num">runs</th><th class="num">distinct sequences</th><th class="num">mean pairwise edit distance</th><th class="num">identical pairs</th><th class="num">steps min–max</th><th class="num">tokens min–max</th></tr>`;
  const grp = by(R, r => `${r.model} × ${r.harness_id} × ${r.task_id}`); let shown = 0; const grpRows = Array.from(grp.entries()).filter(([, rs]) => rs.length >= 2);
  grpRows.forEach(([g, rs]) => { if (shown++ >= 24) return; const seqs = rs.map(seqOf); let dsum = 0, same = 0, pairs = 0; for (let i = 0; i < seqs.length; i++) for (let j = i + 1; j < seqs.length; j++) { const d = levenshtein(seqs[i], seqs[j]); dsum += d; pairs++; if (!d) same++; } const toks = rs.map(tokOf);
    h += `<tr><td>${esc(g)}</td><td class="num">${rs.length}</td><td class="num">${uniq(seqs).length}</td><td class="num">${fmt(dsum / (pairs || 1), 1)}</td><td class="num">${pct(same / (pairs || 1))}</td><td class="num">${Math.min(...rs.map(r => r.steps))}–${Math.max(...rs.map(r => r.steps))}</td><td class="num">${ints(Math.min(...toks))}–${ints(Math.max(...toks))}</td></tr>`; });
  h += `</table></div>${grpRows.length > 24 ? `<p class="small">first 24 of ${grpRows.length} cell × task groups; narrow the filter to see the rest.</p>` : ""}`;
  const pass = G.filter(r => r[key]).map(r => r.steps), fail = G.filter(r => !r[key]).map(r => r.steps);
  h += `<h3><span class="n">5</span> Steps by outcome, and how runs end</h3><div class="row"><div class="col narrow"><div class="small">steps, passing runs (n=${pass.length})</div>${svgHist(pass, { lo: 0, hi: Math.max(...R.map(r => r.steps)) + 1, color: "#17A398" })}<div class="small">steps, failing runs (n=${fail.length})</div>${svgHist(fail, { lo: 0, hi: Math.max(...R.map(r => r.steps)) + 1, color: "#E4572E" })}</div><div class="col">${svgBar(exitMix(R).map(([k, v]) => ({ label: k, value: v, text: pct(v, 1), color: k === "submitted" ? "#17A398" : "#9CA3AF" })), { max: 1 })}<div class="small">exit reasons: everything that is not "submitted" is an UNRESOLVED run, ended by the harness</div></div></div>`;
  return h;
}

// ============================================================ 7. Attribution
function vAttr() {
  const R = filtered(), key = oracleKey(); const G = graded(R, key); if (!G.length) return `<h2>Attribution</h2>` + empty("No graded runs under this oracle.");
  const rows = attribution(R, key).sort((a, b) => b[S.sortAttr] - a[S.sortAttr]);
  const F = G.filter(r => !r[key]).length;
  let h = `<h2>Spectrum-based attribution over trajectories</h2><p class="claim">Rows are runs, columns are binary trajectory features, "failing" is the oracle saying no. susp(f) = e<sub>f</sub> / √(F · (e<sub>f</sub> + e<sub>p</sub>)), the Ochiai formula fault localisation uses on statements. Read both rate columns: a feature common in failures and successes ranks high from base rate alone. Correlation, not cause.</p>`;
  h += `<div class="card"><div class="form"><label>steps ><input type="number" data-act="thr" data-k="steps" value="${S.thr.steps}"></label><label>repeated calls ><input type="number" data-act="thr" data-k="repeated" value="${S.thr.repeated}"></label><label>patch lines ><input type="number" data-act="thr" data-k="lines" value="${S.thr.lines}"></label><label>files edited ><input type="number" data-act="thr" data-k="files" value="${S.thr.files}"></label><label>first edit after step<input type="number" data-act="thr" data-k="first_edit" value="${S.thr.first_edit}"></label><label>sort by<select data-act="sortAttr"><option value="ochiai" ${S.sortAttr === "ochiai" ? "selected" : ""}>Ochiai</option><option value="tarantula" ${S.sortAttr === "tarantula" ? "selected" : ""}>Tarantula</option><option value="rf" ${S.sortAttr === "rf" ? "selected" : ""}>rate in failures</option></select></label></div><div class="small" style="margin-top:6px">${G.length} graded runs · ${F} failing (F) · ${G.length - F} passing (P). Thresholds are yours to argue about; the ranking is only as meaningful as the features. Write your own feature as a query in the Queries view.</div></div>`;
  h += `<div class="tbl"><table><tr><th>feature</th><th class="num">e<sub>f</sub></th><th class="num">e<sub>p</sub></th><th class="num">rate in failures</th><th class="num">rate in successes</th><th class="num">Ochiai</th><th class="num">Tarantula</th><th class="num">risk ratio</th><th></th></tr>`;
  rows.forEach(f => { const rr = riskRatio(f.ef, f.ep, F - f.ef, (G.length - F) - f.ep); h += `<tr class="click" data-act="attrOpen" data-id="${esc(f.id)}"><td><b>${esc(f.id)}</b><div class="small">${esc(f.label)}</div></td><td class="num">${f.ef}</td><td class="num">${f.ep}</td><td class="num">${pct(f.rf)}</td><td class="num">${pct(f.rp)}</td><td class="num"><b>${fmt(f.ochiai, 3)}</b></td><td class="num">${fmt(f.tarantula, 3)}</td><td class="num">${Number.isFinite(rr.rr) ? fmt(rr.rr, 2) : "n/a"}${Number.isFinite(rr.lo) ? `<div class="small">${ciText(rr.lo, rr.hi, 1)}</div>` : ""}</td><td class="small">${f.carriers.length} runs ${S.attrOpen === f.id ? "▾" : "▸"}</td></tr>`;
    if (S.attrOpen === f.id) { h += `<tr><td colspan="9" style="background:var(--card2)"><div class="toolbar"><span class="small">runs carrying this feature</span>${f.carriers.length ? `<button class="btn small sec" data-act="multiSet" data-keys="${esc(f.carriers.slice(0, 12).map(r => r.key).join(","))}">compare first 12</button>` : ""}</div><div class="row">${f.carriers.slice(0, 60).map(r => `<span class="cellpick" data-act="sel" data-key="${esc(r.key)}">${esc(runShort(r))} ${esc(r.task_id)} ${esc(r.harness_id)} ${outBadge(outcome(r, key))}</span>`).join("")}${f.carriers.length > 60 ? `<span class="small">… ${f.carriers.length - 60} more</span>` : ""}</div></td></tr>`; } });
  h += `</table></div>`;
  const top = rows[0];
  if (top) h += `<div class="callout">Top feature: <b>${esc(top.id)}</b>, present in ${pct(top.rf)} of failures and ${pct(top.rp)} of successes. Before calling it a cause, ask: is it a symptom of failing (a run that cannot find the bug keeps looping), a cause (skipping verification lets a wrong patch through), or a harness artefact (a step cap that ends every long run the same way)? The separating experiment is a harness change with the same model.</div>`;
  // per-cell breakdown of the top 4 features
  const cells = uniq(R.map(cellOf)); if (cells.length > 1) { const top4 = rows.slice(0, 4); h += `<h3><span class="n">2</span> Feature rate by cell (does the feature travel with the harness?)</h3><div class="tbl"><table><tr><th>cell</th><th class="num">runs</th><th class="num">pass</th>${top4.map(f => `<th class="num">${esc(f.id)}</th>`).join("")}</tr>${cells.map(c => { const rs = G.filter(r => cellOf(r) === c); const defs = featureDefs(); return `<tr><td><b>${esc(c.replace("|", " · "))}</b></td><td class="num">${rs.length}</td><td class="num">${pct(passRate(rs, key))}</td>${top4.map(f => { const d = defs.find(x => x[0] === f.id); return `<td class="num">${pct(mean(rs.map(r => d[2](featOf(r)) ? 1 : 0)))}</td>`; }).join("")}</tr>`; }).join("")}</table></div><p class="small">A feature whose rate changes with the harness at a fixed model is a harness artefact or a harness effect; one that stays put across harnesses belongs to the model or the tasks.</p>`; }
  return h;
}

// ============================================================ 8. Telemetry
function vTele() {
  const R = filtered(), key = oracleKey(); if (!R.length) return `<h2>Telemetry</h2>` + empty();
  let h = `<h2>Telemetry: the ledger is the instrument</h2><p class="claim">Every number here comes from spans that use OpenTelemetry GenAI attribute names, so what you learn in the lab maps onto production traces. Cost is the endpoint's reported charge where available (OpenRouter) and tokens × price otherwise; the conventions carry no cost attribute.</p>`;
  const groups = groupsOf(R); const ref = Array.from(groups.keys()).find(k => k.endsWith("|baseline")) || Array.from(groups.keys())[0];
  const refCop = costOfPass(groups.get(ref), key);
  h += `<div class="tbl"><table><tr><th>cell (results · model · harness)</th><th class="num">runs</th><th class="num">pass@1</th><th class="num">tok/run</th><th class="num">p95 tok/run</th><th class="num">tok/solve</th><th class="num">$/run</th><th class="num">cost of pass</th><th class="num">agency tax vs ${esc(ref.split("|").slice(1).join(" · "))}</th><th class="num">model ms/run</th><th class="num">calls/run</th><th class="num">in:out</th></tr>`;
  Array.from(groups.entries()).forEach(([gk, rs]) => { const toks = rs.map(tokOf).sort((a, b) => a - b); const p95 = toks[Math.min(toks.length - 1, Math.floor(0.95 * toks.length))]; const cop = costOfPass(rs, key); const inn = sum(rs.map(r => r.input_tokens || 0)), out = sum(rs.map(r => r.output_tokens || 0));
    h += `<tr class="click" data-act="cellsel" data-key="${esc(gk)}"><td>${esc(gk.split("|").join(" · "))}</td><td class="num">${rs.length}</td><td class="num">${pct(passRate(rs, key), 1)}</td><td class="num">${ints(mean(toks))}</td><td class="num">${ints(p95)}</td><td class="num">${ints(tokensPerSolve(rs, key))}</td><td class="num">${usd(mean(rs.map(r => r.cost_usd || 0)))}</td><td class="num"><b>${usd(cop)}</b></td><td class="num">${Number.isFinite(cop) && Number.isFinite(refCop) && refCop ? fmt(cop / refCop, 2) + "×" : "n/a"}</td><td class="num">${ints(mean(rs.map(latencyOf)))}</td><td class="num">${fmt(mean(rs.map(r => r.steps)), 1)}</td><td class="num">${out ? fmt(inn / out, 0) + ":1" : "n/a"}</td></tr>`; });
  h += `</table></div>`;
  const cells = Array.from(groups.entries()).map(([k, rs], i) => { const n = graded(rs, key).length, p = passRate(rs, key); return { key: k, label: k.split("|").slice(1).join(" · "), x: costOfPass(rs, key), y: p, err: wilson(Math.round(p * n), n), color: SERIES[i % SERIES.length], title: `${k.split("|").join(" · ")}: pass ${pct(p, 1)} · ${usd(costOfPass(rs, key))} per pass`, act: "cellsel" }; });
  h += `<div class="row"><div class="col">${svgScatter(cells, { xlog: true, xlabel: "cost of pass (USD, log)", ylabel: "pass rate", ymax: 1, frontier: true, xfmt: x => usd(x), yfmt: y => pct(y), w: 480, h: 280 })}<div class="small">Cost of pass = mean cost per run ÷ pass rate: what a correct answer costs once failures are paid for. Cells above and to the left of the dashed frontier do not exist; cells below it are dominated.</div></div>`;
  h += `<div class="col">${svgBar(Array.from(groups.entries()).map(([gk, rs]) => ({ label: gk.split("|").slice(1).join(" · "), value: Math.min(tokensPerSolve(rs, key), 1e9), text: ints(tokensPerSolve(rs, key)) })), { w: 480, lw: 210, color: "#3B6FD9" })}<div class="small">tokens per solved task: the column Vats & Golev found to spread 40× across harnesses at equal pass rate</div></div></div>`;
  // per task cost
  const tasks = uniq(R.map(r => r.task_id)).sort().slice(0, 40);
  h += `<h3><span class="n">2</span> Where the money goes, per task</h3><div class="tbl"><table><tr><th>task</th><th class="num">runs</th><th class="num">pass</th><th class="num">mean tokens</th><th class="num">mean cost</th><th class="num">cost of pass</th><th class="num">mean steps</th><th class="num">share of spend</th></tr>${tasks.map(t => { const rs = R.filter(r => r.task_id === t); return `<tr><td><b>${esc(t)}</b></td><td class="num">${rs.length}</td><td class="num">${pct(passRate(rs, key))}</td><td class="num">${ints(mean(rs.map(tokOf)))}</td><td class="num">${usd(mean(rs.map(r => r.cost_usd || 0)))}</td><td class="num">${usd(costOfPass(rs, key))}</td><td class="num">${fmt(mean(rs.map(r => r.steps)), 1)}</td><td class="num">${pct(sum(rs.map(r => r.cost_usd || 0)) / (sum(R.map(r => r.cost_usd || 0)) || 1))}</td></tr>`; }).join("")}</table></div>`;
  const sel = S.sel ? runByKey(S.sel) : R[0];
  h += `<div class="row"><div class="col"><h3><span class="n">3</span> Cost accumulation for one run (${esc(sel.run_id)}, ${esc(cellLabel(sel))})</h3>${svgTokens(spansOf(sel), { w: 640, h: 140 })}<p class="small">Input tokens grow with the transcript: each call re-sends the history the harness keeps. A context-management rule (C in H) changes this curve directly.</p></div>`;
  h += `<div class="col narrow"><h3><span class="n">4</span> Attribute names in the ledger</h3><div class="card"><table style="width:100%"><tr><th>span</th><th>attributes</th></tr><tr><td>invoke_agent</td><td class="mono">harness (full config), exit_reason, total_tokens, cost_usd</td></tr><tr><td>chat</td><td class="mono">gen_ai.operation.name, gen_ai.request.model, gen_ai.usage.input_tokens, gen_ai.usage.output_tokens, gen_ai.response.finish_reasons, duration_ms, cost_usd</td></tr><tr><td>execute_tool</td><td class="mono">gen_ai.tool.name, args, status, duration_ms, result_preview, kind (imported runs)</td></tr><tr><td>edit</td><td class="mono">path, lines_added, lines_removed, tool</td></tr><tr><td>boundary_event</td><td class="mono">kind, tool, args, status (blocked | allowed)</td></tr><tr><td>grade</td><td class="mono">visible, hidden, strong, tests_modified</td></tr></table></div></div></div>`;
  return h;
}

// ============================================================ 9. Integrity
function vInteg() {
  const R = filtered(); if (!R.length) return `<h2>Integrity</h2>` + empty();
  let h = `<h2>Passing is not correct</h2><p class="claim">Three oracles graded the same final workspaces: the visible tests the agent saw, the hidden suite, and a strengthened suite. The disagreements are the measurement error of the benchmark, and they are not symmetric across harnesses.</p>`;
  const withV = R.filter(r => r.visible_pass != null), withH = R.filter(r => r.hidden_pass != null), withS = R.filter(r => r.strong_pass != null);
  h += `<div class="tiles">${tile(pct(passRate(R, "visible_pass"), 1), "pass rate, visible tests (self-report)", `what the agent could check · n=${withV.length}`)}${tile(pct(passRate(R, "hidden_pass"), 1), "pass rate, hidden tests", `the benchmark's oracle · n=${withH.length}`)}${tile(pct(passRate(R, "strong_pass"), 1), "pass rate, strengthened tests", `hidden + augmented · n=${withS.length}`)}${tile(pct(mean(R.map(r => r.tests_modified ? 1 : 0)), 1), "runs that modified tests", "oracle tampering, blocked or not")}</div>`;
  const conf = (ka, kb, la, lb) => { const rs = R.filter(r => r[ka] != null && r[kb] != null); if (!rs.length) return `<div class="card"><h4>${esc(la)} vs ${esc(lb)}</h4><div class="small">no runs graded by both</div></div>`; const c = { tt: 0, tf: 0, ft: 0, ff: 0 }; rs.forEach(r => { c[(r[ka] ? "t" : "f") + (r[kb] ? "t" : "f")]++; }); const n = rs.length; const sens = c.tt + c.ft ? c.tt / (c.tt + c.ft) : NaN, spec = c.tf + c.ff ? c.ff / (c.tf + c.ff) : NaN; return `<div class="card"><h4>${esc(la)} vs ${esc(lb)}</h4><table><tr><th></th><th>${esc(lb)} ✔</th><th>${esc(lb)} ✘</th></tr><tr><td>${esc(la)} ✔</td><td class="num" style="background:var(--ok-bg)">${c.tt}</td><td class="num" style="background:var(--bad-bg)"><b>${c.tf}</b></td></tr><tr><td>${esc(la)} ✘</td><td class="num" style="background:var(--warn-bg)">${c.ft}</td><td class="num">${c.ff}</td></tr></table><div class="small" style="margin-top:6px">treating ${esc(lb)} as truth: sensitivity of ${esc(la)} = ${fmt(sens)}, specificity = ${fmt(spec)} · κ = ${fmt(kappa(rs.map(r => !!r[ka]), rs.map(r => !!r[kb])))} · ${pct(c.tf / n, 1)} of runs are "${esc(la)} passes, ${esc(lb)} fails"</div></div>`; };
  h += `<div class="row"><div class="col">${conf("visible_pass", "hidden_pass", "visible", "hidden")}</div><div class="col">${conf("hidden_pass", "strong_pass", "hidden", "strengthened")}</div></div>`;
  const hids = uniq(R.map(r => r.harness_id));
  if (hids.length > 1) {
    const tab = hids.map(hid => { const rs = R.filter(r => r.harness_id === hid); return { hid, v: passRate(rs, "visible_pass"), h: passRate(rs, "hidden_pass"), s: passRate(rs, "strong_pass"), n: rs.length }; });
    const rank = (k) => { const o = tab.filter(x => Number.isFinite(x[k])).sort((a, b) => b[k] - a[k]); return Object.fromEntries(o.map((x, i) => [x.hid, i + 1])); }; const rv = rank("v"), rh = rank("h"), rsn = rank("s");
    h += `<h3><span class="n">2</span> Does the ranking survive a stronger oracle?</h3><div class="tbl"><table><tr><th>harness</th><th class="num">n</th><th class="num">visible</th><th class="num">rank</th><th class="num">hidden</th><th class="num">rank</th><th class="num">strengthened</th><th class="num">rank</th><th class="num">lost hidden → strong</th></tr>${tab.map(x => `<tr><td><b>${esc(x.hid)}</b></td><td class="num">${x.n}</td><td class="num">${pct(x.v, 1)}</td><td class="num">${rv[x.hid] || ""}</td><td class="num">${pct(x.h, 1)}</td><td class="num">${rh[x.hid] || ""}</td><td class="num">${pct(x.s, 1)}</td><td class="num">${rsn[x.hid] && rsn[x.hid] !== rh[x.hid] ? `<b style="color:var(--signal)">${rsn[x.hid]}</b>` : (rsn[x.hid] || "")}</td><td class="num">${Number.isFinite(x.s) ? pct(x.h - x.s, 1) : ""}</td></tr>`).join("")}</table></div>`;
  }
  const leaky = Object.values(B.tasks).filter(t => t.probe && t.probe !== "none");
  if (leaky.length) {
    h += `<h3><span class="n">3</span> Task probes</h3><div class="tbl"><table><tr><th>task</th><th>probe</th><th class="num">pass@1</th><th class="num">mean steps</th><th class="num">mean tokens</th><th class="num">mean patch bytes</th><th>others (mean)</th></tr>`;
    const others = R.filter(r => !leaky.some(t => t.id === r.task_id));
    leaky.forEach(t => { const rs = R.filter(r => r.task_id === t.id); if (!rs.length) return; h += `<tr><td><b>${esc(t.id)}</b><div class="small">${esc(t.title)}</div></td><td>${esc(t.probe)}</td><td class="num">${pct(passRate(rs, "hidden_pass"))}</td><td class="num">${fmt(mean(rs.map(r => r.steps)), 1)}</td><td class="num">${ints(mean(rs.map(tokOf)))}</td><td class="num">${ints(mean(rs.map(r => r.patch_bytes)))}</td><td class="small">pass ${pct(passRate(others, "hidden_pass"))} · steps ${fmt(mean(others.map(r => r.steps)), 1)} · tokens ${ints(mean(others.map(tokOf)))}</td></tr>`; });
    h += `</table></div><p class="small">solution_leak: the fix is in the issue text (SWE-bench+ found 32.67% of passed patches with the solution in the issue or comments). injected: the issue carries an instruction the agent should not follow. ambiguous: the issue underspecifies the behaviour, so a passing patch is one reading of it.</p>`;
  }
  if (B.judge && B.judge.length) {
    h += `<h3><span class="n">4</span> Judge calibration (exercise 4, saved by the script)</h3><div class="tbl"><table><tr><th>judge</th><th class="num">items</th><th class="num">repeats</th><th class="num">raw agreement</th><th class="num">κ</th><th class="num">test-retest</th><th class="num">P(pick A) first / after swap</th><th class="num">position-consistent</th><th class="num">judged-correct length / judged-incorrect</th><th>when</th></tr>${B.judge.map(j => `<tr><td><b>${esc(j.judge)}:${esc(j.model)}</b></td><td class="num">${j.n}</td><td class="num">${j.repeats}</td><td class="num">${pct(j.agreement, 1)}</td><td class="num"><b>${fmt(j.kappa, 2)}</b></td><td class="num">${pct(j.test_retest, 1)}</td><td class="num">${j.pairwise ? fmt(j.pairwise.p_pick_A_first, 2) + " / " + fmt(j.pairwise.p_pick_A_after_swap, 2) : "n/a"}</td><td class="num">${j.pairwise ? pct(j.pairwise.position_consistent) : "n/a"}</td><td class="num">${ints(j.mean_len_judged_correct)} / ${ints(j.mean_len_judged_incorrect)}</td><td class="small">${esc(j.generated_at)}</td></tr>`).join("")}</table></div><p class="small">Agreement minus chance is κ. A judge can be perfectly repeatable and still biased (P(pick A) far from 0.5 after the swap): the consistency-bias paradox.</p>`;
  }
  return h;
}

// ============================================================ 10. Experiment
const FACTORS = { model: "model", harness_id: "harness", results: "results dir", task_id: "task" };
function vExp() {
  const R = filtered(), key = oracleKey(); const G = graded(R, key); if (!G.length) return `<h2>Experiment</h2>` + empty("No graded runs under this oracle.");
  const fa = S.expFA, fb = S.expFB; const A = uniq(G.map(r => r[fa])), Bv = uniq(G.map(r => r[fb])).slice(0, 10);
  let h = `<h2>From benchmark to experiment</h2><p class="claim">Y<sub>ijk</sub> = μ + α<sub>i</sub> + β<sub>j</sub> + (αβ)<sub>ij</sub> + u<sub>k</sub><sup>task</sup> + ε<sub>ijk</sub>. The interaction term is the question "does this factor help everywhere, or only here?". A benchmark row cannot answer it; a factorial design can.</p>`;
  h += `<div class="toolbar"><label class="small">factor A <select data-act="expFA">${Object.entries(FACTORS).map(([k, v]) => `<option value="${k}" ${fa === k ? "selected" : ""}>${v}</option>`).join("")}</select></label><label class="small">factor B <select data-act="expFB">${Object.entries(FACTORS).map(([k, v]) => `<option value="${k}" ${fb === k ? "selected" : ""}>${v}</option>`).join("")}</select></label><span class="small">block: task · outcome: ${S.oracle} oracle</span></div>`;
  const cells = new Map(); G.forEach(r => { const k = r[fa] + "|" + r[fb]; if (!cells.has(k)) cells.set(k, []); cells.get(k).push(r); });
  h += `<h3><span class="n">1</span> Cell means (pass rate, n) · ${esc(FACTORS[fa])} × ${esc(FACTORS[fb])}</h3><div class="tbl"><table><tr><th>${esc(FACTORS[fa])} \\ ${esc(FACTORS[fb])}</th>${Bv.map(x => `<th>${esc(x)}</th>`).join("")}</tr>`;
  A.slice(0, 12).forEach(m => { h += `<tr><td><b>${esc(m)}</b></td>${Bv.map(x => { const rs = cells.get(m + "|" + x); if (!rs) return `<td class="small">—</td>`; const c = rs.filter(r => r[key]).length; const w = wilson(c, rs.length); const k = m + "|" + x; return `<td><span class="cellpick ${S.expA === k ? "on" : ""}" data-act="expA" data-k="${esc(k)}" title="click: set as A">${pct(c / rs.length, 0)} <span class="small">n=${rs.length}</span></span><span class="cellpick ${S.expB === k ? "on" : ""}" data-act="expB" data-k="${esc(k)}" title="click: set as B">B</span><div class="small">${ciText(w[0], w[1])}</div></td>`; }).join("")}</tr>`; });
  h += `</table></div>`;
  if (A.length >= 2 && Bv.length >= 2 && fa !== fb) {
    const series = A.slice(0, 8).map((m, i) => ({ name: m, color: SERIES[i % SERIES.length], points: Bv.map((x, j) => { const rs = cells.get(m + "|" + x); return rs ? [j, passRate(rs, key)] : null; }).filter(Boolean) }));
    const balanced = Bv.filter(x => A.every(m => cells.has(m + "|" + x))); const balA = A.filter(m => balanced.every(x => cells.has(m + "|" + x)));
    const f = balanced.length >= 2 && balA.length >= 2 ? factorial(G.filter(r => balanced.includes(r[fb]) && balA.includes(r[fa])), fa, fb, "task_id", key) : null;
    h += `<h3><span class="n">2</span> Interaction plot and variance decomposition${f && (balanced.length < Bv.length || balA.length < A.length) ? ` <span class="small">(decomposition on the balanced subset: ${esc(balA.join(", "))} × ${esc(balanced.join(", "))})</span>` : ""}</h3><div class="row"><div class="col">${svgLines(series, { xticks: Bv.map((_, j) => j), xfmt: j => Bv[j], ymax: 1, xlabel: FACTORS[fb], h: 260, w: 520 })}<div class="small">Parallel lines: the effect of ${esc(FACTORS[fb])} transfers across ${esc(FACTORS[fa])} levels (additive). Crossing lines: it is level-specific and a single-level ablation would mislead.</div></div>`;
    if (f) h += `<div class="col"><div class="tbl"><table><tr><th>term</th><th class="num">SS</th><th class="num">df</th><th class="num">MS</th><th class="num">F</th><th class="num">share of SS</th></tr>${f.rows.map(r => `<tr><td>${esc(r.term)}</td><td class="num">${fmt(r.ss, 2)}</td><td class="num">${r.df}</td><td class="num">${fmt(r.ms, 4)}</td><td class="num">${fmt(r.F, 2)}</td><td class="num"><b>${pct(r.share, 1)}</b></td></tr>`).join("")}</table></div><div class="small">n = ${f.n} runs · grand mean ${fmt(f.mu, 3)}. The residual is run-to-run noise inside a cell; the task block is the difficulty spread. Whatever is left for the two factors is what a leaderboard reports as if it were everything.</div></div>`;
    h += `</div>`;
    // contrasts within each A level
    if (fb !== "task_id") { h += `<h3><span class="n">3</span> All pairwise contrasts of ${esc(FACTORS[fb])}, paired over tasks, within each ${esc(FACTORS[fa])}</h3><div class="tbl"><table><tr><th>${esc(FACTORS[fa])}</th><th>contrast (B − A)</th><th class="num">Δ</th><th class="num">95% task-bootstrap</th><th class="num">tasks</th><th>verdict</th></tr>`; let nC = 0;
      A.slice(0, 6).forEach(m => { for (let i = 0; i < Bv.length; i++) for (let j = i + 1; j < Bv.length; j++) { const a = cells.get(m + "|" + Bv[i]), b = cells.get(m + "|" + Bv[j]); if (!a || !b) continue; const p = pairedBootstrap(a, b, key); if (!p.n) continue; nC++; const covers = p.lo <= 0 && p.hi >= 0; h += `<tr><td>${esc(m)}</td><td>${esc(Bv[j])} − ${esc(Bv[i])}</td><td class="num">${(p.mean >= 0 ? "+" : "") + pct(p.mean, 1)}</td><td class="num">${ciText(p.lo, p.hi)}</td><td class="num">${p.n}</td><td>${covers ? '<span class="badge na">covers zero</span>' : `<span class="badge ${p.mean > 0 ? "ok" : "bad"}">${p.mean > 0 ? "B higher" : "A higher"}</span>`}</td></tr>`; } });
      h += `</table></div><p class="small">${nC} contrasts. With ${nC} comparisons at 95%, expect about ${fmt(nC * 0.05, 1)} to exclude zero by chance; a Bonferroni-adjusted interval would be at ${nC ? (100 - 5 / nC).toFixed(1) : 95}%.</p>`; }
  } else h += `<div class="callout">The factorial needs at least two levels of each factor in the filter (and two different factors).</div>`;
  const a = S.expA && cells.get(S.expA), b = S.expB && cells.get(S.expB);
  h += `<h3><span class="n">4</span> Can we conclude A &gt; B?</h3>`;
  if (!a || !b) return h + `<p class="small">Click a cell above to set A, the "B" tag next to another to set B.</p>`;
  const ca = a.filter(r => r[key]).length, cb = b.filter(r => r[key]).length, pa = ca / a.length, pb = cb / b.length, wa = wilson(ca, a.length), wb = wilson(cb, b.length);
  const paired = pairedBootstrap(b, a, key); const need = powerN(pa, pb);
  h += `<div class="tiles">${tile(`${ca}/${a.length} = ${pct(pa, 0)}`, "A: " + S.expA.replace("|", " × "), "Wilson " + ciText(wa[0], wa[1]))}${tile(`${cb}/${b.length} = ${pct(pb, 0)}`, "B: " + S.expB.replace("|", " × "), "Wilson " + ciText(wb[0], wb[1]))}${tile((pa - pb >= 0 ? "+" : "") + pct(pa - pb, 1), "A − B, paired over tasks", paired.n ? "95% " + ciText(-paired.hi, -paired.lo) + " · " + paired.n + " tasks" : "no shared tasks")}${tile(Number.isFinite(need) ? ints(need) + " per arm" : "∞", "runs needed to detect this difference", "two-proportion, α = 0.05, power 0.8")}</div>`;
  const overlap = wa[0] <= wb[1] && wb[0] <= wa[1];
  h += `<div class="callout ${overlap ? "" : "teal"}">${a.length === 1 && b.length === 1 ? "One run each: 1/1 versus 0/1 looks like 100% versus 0%. Wilson says " + ciText(wa[0], wa[1]) + " versus " + ciText(wb[0], wb[1]) + ". Nothing can be concluded." : (overlap ? "The intervals overlap and the paired interval " + (paired.n && (-paired.hi <= 0 && -paired.lo >= 0) ? "covers zero" : "is wide") + ". At this n the honest answer is: not yet. The number of runs it would take is on the right." : "The intervals separate. Report the paired difference with its interval, the n, and the cell definition, not the two point estimates.")}</div>`;
  // power curve + wrong-winner simulation
  const base = Math.max(0.05, Math.min(0.95, pa)); const deltas = [0.02, 0.03, 0.05, 0.075, 0.1, 0.15, 0.2, 0.3]; const pts = deltas.map(d => [d, Math.min(5000, powerN(base, Math.max(0.01, Math.min(0.99, base - d))))]);
  const ta = taskTable(a, key), tb = taskTable(b, key); const shared = Object.keys(ta).filter(t => tb[t]); const pAt = shared.map(t => ta[t].p), pBt = shared.map(t => tb[t].p);
  h += `<div class="row"><div class="col">${svgLines([{ name: `runs per arm at power 0.8 (baseline p = ${fmt(base, 2)})`, color: "#E4572E", points: pts }], { xlabel: "difference in pass rate to detect", xticks: deltas, xfmt: d => pct(d), yfmt: y => ints(y), h: 240, w: 480, hline: a.length })}<div class="small">The dashed line is the n you have per arm now. Everything to the left of where the curve crosses it is invisible to this experiment.</div></div>`;
  if (shared.length >= 2) { const ks = [1, 2, 3, 5, 10]; const sims = ks.map(k => ({ k, ...wrongWinner(pAt, pBt, k) })); h += `<div class="col narrow"><h4>How often does the wrong arm win? (Monte-Carlo, ${shared.length} shared tasks, per-task p from the data)</h4><div class="tbl"><table><tr><th class="num">repeats per task</th><th class="num">wrong winner</th><th class="num">tie</th></tr>${sims.map(s => `<tr><td class="num">${s.k}</td><td class="num"><b>${pct(s.wrong, 1)}</b></td><td class="num">${pct(s.ties, 1)}</td></tr>`).join("")}</table></div><div class="small">Draw Bernoulli outcomes per task with each arm's observed per-task rate, k repeats, 2,000 simulations; count how often the arm with the lower true mean ends up ahead. With one repeat, that number is the leaderboard's error rate on this pair.</div></div>`; }
  h += `</div>`;
  return h;
}

// ============================================================ 11. Report card
function reportMd() {
  const R = filtered(), key = oracleKey(); const G = graded(R, key); if (!G.length) return "No graded runs in filter.";
  const agg = aggregate(R, key), tt = agg.tt, tasks = Object.keys(tt), ci = bootstrapCI(tasks.map(t => tt[t].p));
  const hids = uniq(R.map(r => r.harness_id)), models = uniq(R.map(r => r.model)); const hcfg = B.harnesses[hids[0]] || {};
  const strong = aggregate(R, "strong_pass"), vis = aggregate(R, "visible_pass"), hid = aggregate(R, "hidden_pass");
  const L = [];
  L.push(`# Evaluation report card`, ``, `Generated ${new Date().toISOString().slice(0, 16).replace("T", " ")} by AgentLab Console from ${uniq(R.map(r => r.results)).join(", ")}`, ``);
  L.push(`## 1. The cell (what exactly was measured)`, ``, `| field | value |`, `|---|---|`, `| model(s) | ${models.join(", ")} |`, `| harness(es) | ${hids.join(", ")} |`);
  if (hids.length === 1) L.push(`| harness config | tools: ${(hcfg.tools || []).join(", ")}; policy: ${hcfg.policy}; max_steps: ${hcfg.max_steps}; context_window: ${hcfg.context_window || "full"}; temperature: ${hcfg.temperature}; system prompt ${(hcfg.system_prompt || "").length} chars (full text in the first span of every ledger) |`);
  L.push(`| tasks | ${tasks.length} (${tasks.slice(0, 20).join(", ")}${tasks.length > 20 ? ", …" : ""}) |`, `| protocol | ${Math.max(...R.map(r => r.repeat_index + 1))} repeats per task; oracle = ${S.oracle} test suite on a pristine copy of the workspace |`, `| runs | ${R.length} (${G.length} graded under this oracle) |`, ``);
  L.push(`## 2. Outcome (as a distribution, not a number)`, ``, `| metric | value |`, `|---|---|`, `| pass@1 (mean over tasks) | ${fmt(agg.pass1, 3)}  95% task-bootstrap CI [${fmt(ci[0], 3)}, ${fmt(ci[1], 3)}] |`);
  [2, 3, 5].forEach(k => { if (agg["pass@" + k] != null) L.push(`| pass@${k} / pass^${k} | ${fmt(agg["pass@" + k], 3)} / ${fmt(agg["pass^" + k], 3)} |`); });
  L.push(`| flip rate (tasks with mixed outcomes) | ${fmt(flipRate(R, key))} |`, `| pass@1 under visible / hidden / strengthened tests | ${vis ? fmt(vis.pass1, 3) : "n/a"} / ${hid ? fmt(hid.pass1, 3) : "n/a"} / ${strong ? fmt(strong.pass1, 3) : "n/a"} |`, `| exit reasons | ${exitMix(R).map(([k, v]) => `${k}=${fmt(v)}`).join(", ")} |`, ``);
  L.push(`Per task:`, ``, `| task | n | pass@1 | Wilson 95% | pass^3 |`, `|---|---|---|---|---|`);
  tasks.slice(0, 40).forEach(t => { const v = tt[t], w = wilson(v.c, v.n); L.push(`| ${t} | ${v.n} | ${fmt(v.p)} | [${fmt(w[0])}, ${fmt(w[1])}] | ${v.n >= 3 ? fmt(passPowK(v.c, v.n, 3)) : "n/a"} |`); });
  L.push(``, `## 3. Conduct (from the ledger)`, ``, `| metric | value |`, `|---|---|`, `| runs with ≥1 boundary event | ${fmt(boundaryAny(R))} |`, `| runs that modified tests | ${fmt(mean(R.map(r => r.tests_modified ? 1 : 0)))} |`, `| runs that verified after their last edit | ${fmt(verifiedRate(R))} |`, `| runs that never ran tests | ${fmt(mean(R.map(r => (featOf(r).n_test || 0) + (featOf(r).n_bash || 0) === 0 ? 1 : 0)))} |`, ``);
  L.push(`## 4. Cost`, ``, `| metric | value |`, `|---|---|`, `| mean tokens per run | ${ints(mean(R.map(tokOf)))} |`, `| tokens per solve | ${ints(tokensPerSolve(R, key))} |`, `| mean cost per run | ${usd(mean(R.map(r => r.cost_usd || 0)))} |`, `| cost of pass | ${usd(costOfPass(R, key))} |`, ``);
  const top = attribution(R, key).sort((a, b) => b.ochiai - a.ochiai).slice(0, 3);
  L.push(`## 5. Integrity checks`, ``, `- self-report vs oracle: ${fmt(mean(R.filter(r => r.visible_pass != null && r.hidden_pass != null).map(r => r.visible_pass && !r.hidden_pass ? 1 : 0)), 3)} of runs pass the visible tests and fail the hidden ones`, `- weak oracle: ${fmt(mean(R.filter(r => r.hidden_pass != null && r.strong_pass != null).map(r => r.hidden_pass && !r.strong_pass ? 1 : 0)), 3)} of runs pass the hidden tests and fail the strengthened ones`, `- task probes present: ${Object.values(B.tasks).filter(t => t.probe !== "none" && tasks.includes(t.id)).map(t => `${t.id} (${t.probe})`).join(", ") || "none"}`, `- top trajectory features by Ochiai: ${top.map(f => `${f.id} (${fmt(f.ochiai, 2)}; in ${pct(f.rf)} of failures, ${pct(f.rp)} of successes)`).join("; ")}`, ``);
  if (S.qSaved.length) { L.push(`## 5b. Saved trajectory queries`, ``, `| query | regex | matches | pass in | pass out | risk ratio |`, `|---|---|---|---|---|---|`); S.qSaved.forEach(sq => { const m = queryMatcher(sq); if (!m.fn) return; const st = predicateStats(R, m.fn, key); L.push(`| ${sq.name || "(unnamed)"} | \`${sq.re}\` | ${st.matches.length} | ${fmt(st.passIn)} | ${fmt(st.passOut)} | ${Number.isFinite(st.rr.rr) ? fmt(st.rr.rr, 2) : "n/a"} |`); }); L.push(``); }
  L.push(`## 6. What this card does not tell you`, ``, `- whether the produced code is secure (no security oracle was run)`, `- whether the tasks are contaminated or leaked beyond the probes above`, `- whether the ranking of harnesses would hold on a different model (see the Experiment view for the interaction term)`, `- anything about tasks outside this set; the interval is over these tasks resampled, not over the population of issues`, ``);
  return L.join("\n");
}
function vReport() {
  const md = reportMd();
  return `<h2>The report card</h2><p class="claim">The lecture's closing recipe as an artefact. It is generated from the current filter, so change the oracle or the harness and regenerate. Copy it into your notes; the lab hand-in is this text plus your answers.</p><div class="toolbar"><button class="btn" data-act="copy">Copy Markdown</button><button class="btn sec" data-act="csv">Export runs as CSV</button><span class="small" id="copy_msg"></span></div><textarea class="md" id="report_md" readonly>${esc(md)}</textarea>`;
}

// ============================================================ help drawer
function helpHtml() {
  return `<div class="drawer" id="drawer"><button class="btn small sec close" data-act="help">close</button><h2>Formulas and shortcuts</h2>
  <dl>
  <dt>Cell</dt><dd>(model, harness, task, environment, budget, oracle). A run is one draw from the cell's distribution; the randomness R is what repeats sample.</dd>
  <dt>pass@1</dt><dd>mean over tasks of the per-task pass rate c/n. Reported with a task-bootstrap interval: resample tasks with replacement, recompute the mean, take the 2.5th and 97.5th percentiles.</dd>
  <dt>Wilson interval</dt><dd><span class="mono">(p̂ + z²/2n ± z√(p̂(1−p̂)/n + z²/4n²)) / (1 + z²/n)</span>. Unlike Wald it does not collapse to a point at p̂ = 0 or 1.</dd>
  <dt>pass@k, pass^k</dt><dd><span class="mono">pass@k = 1 − C(n−c, k)/C(n, k)</span> (at least one of k passes; Chen et al. 2021). <span class="mono">pass^k = C(c, k)/C(n, k)</span> (all k pass; τ-bench). Both unbiased for any n ≥ k.</dd>
  <dt>Paired Δ<sub>H</sub></dt><dd>mean over tasks of (B's per-task rate − A's per-task rate), tasks resampled for the interval. Pairing removes the task-difficulty variance from the comparison.</dd>
  <dt>Cost of pass</dt><dd>mean cost per run ÷ pass rate: what one correct answer costs once failures are paid for. Agency tax: cost of pass relative to a reference harness.</dd>
  <dt>Tokens per solve</dt><dd>total tokens across all runs ÷ number of passing runs.</dd>
  <dt>Ochiai</dt><dd><span class="mono">e_f / √(F · (e_f + e_p))</span> with e_f, e_p the failing and passing runs that carry the feature and F all failing runs. Tarantula: <span class="mono">(e_f/F) / (e_f/F + e_p/P)</span>. Fault localisation formulas, with runs as the spectrum.</dd>
  <dt>Risk ratio</dt><dd>P(fail | feature) / P(fail | no feature), with a log-normal 95% interval.</dd>
  <dt>Cohen's κ</dt><dd><span class="mono">(p_o − p_e)/(1 − p_e)</span>: agreement beyond chance. 0 is chance, 1 is perfect.</dd>
  <dt>Sensitivity, specificity</dt><dd>of one oracle against another treated as truth: P(pass | truly pass), P(fail | truly fail).</dd>
  <dt>Two-factor decomposition</dt><dd><span class="mono">SS_total = SS_A + SS_B + SS_AB + SS_task + SS_cell×task + SS_residual</span>, balanced design, textbook sums of squares. Shares are SS / SS_total.</dd>
  <dt>Runs per arm</dt><dd><span class="mono">n ≈ (z_{1−α/2} + z_{1−β})² [p_A(1−p_A) + p_B(1−p_B)] / (p_A − p_B)²</span>, α = 0.05, power 0.8.</dd>
  <dt>Predicates</dt><dd>P_verify: a test after the last edit. G(edit ⇒ F test): every edit eventually tested (LTL). P_scope: no edit under tests/. read ≺ write: every written file was read first. ¬loop: no identical (tool, args) call repeated with no edit in between.</dd>
  <dt>Action alphabet</dt><dd>L list_files · R read/view · F search · W write_file · E edit · T run tests · B bash/other · S submit. Queries are regular expressions over this string.</dd>
  <dt>Edit distance</dt><dd>Levenshtein distance between two action strings; clustering is average-linkage on it.</dd>
  </dl>
  <h3>Keyboard</h3><p><span class="kbd">1</span>…<span class="kbd">9</span> <span class="kbd">0</span> <span class="kbd">-</span> <span class="kbd">=</span> switch view · <span class="kbd">j</span>/<span class="kbd">k</span> next/previous run in the viewer · <span class="kbd">m</span> add the open run to the selection · <span class="kbd">?</span> this drawer · <span class="kbd">t</span> theme · <span class="kbd">Esc</span> close.</p>
  <h3>URL</h3><p>The address bar carries the view, the filters, the oracle and the selected run, so a link opens the same picture on another machine that has the same export.</p></div>`;
}
