// ============================================================ 3. Trajectories
function vTraj() {
  const R = filtered();
  let h = `<h2>Trajectory as first-class data</h2><p class="claim">τ = (s₀, a₀, o₁, s₁, …). Two runs can have the same outcome and nothing else in common. The predicates below are evaluated on the ledger, not on the agent's own account of what it did.</p>`;
  h += `<div class="tabsmall">${[["list", "Run list"], ["viewer", "Viewer"], ["compare", "Compare two"], ["multi", `Compare selected (${S.multi.size})`]].map(([id, l]) => `<button class="${S.trajTab === id ? "on" : ""}" data-act="trajTab" data-v="${id}">${l}</button>`).join("")}<span class="small">shortcuts: <span class="kbd">j</span>/<span class="kbd">k</span> next / previous run · <span class="kbd">m</span> add to selection</span></div>`;
  if (S.trajTab === "list") return h + trajList(R);
  if (S.trajTab === "viewer") return h + trajViewer();
  if (S.trajTab === "multi") return h + trajMulti();
  return h + trajCompare(R);
}
function listRows(R) {
  const key = oracleKey(); let rows = R.slice();
  if (S.trajOutcome) rows = rows.filter(r => outcome(r, key) === S.trajOutcome);
  if (S.trajTask) rows = rows.filter(r => r.task_id === S.trajTask);
  const sorters = { run: (a, b) => a.run_id.localeCompare(b.run_id), task: (a, b) => a.task_id.localeCompare(b.task_id) || a.repeat_index - b.repeat_index, steps: (a, b) => b.steps - a.steps, tokens: (a, b) => tokOf(b) - tokOf(a), cost: (a, b) => (b.cost_usd || 0) - (a.cost_usd || 0), outcome: (a, b) => outcome(a, key).localeCompare(outcome(b, key)), fails: (a, b) => predicates(spansOf(b)).filter(p => p.ok === false).length - predicates(spansOf(a)).filter(p => p.ok === false).length };
  return rows.sort(sorters[S.trajSort] || sorters.run);
}
function trajList(R) {
  const key = oracleKey(); const rows = listRows(R); const PAGE = 100, page = Math.min(S.listPage, Math.max(0, Math.ceil(rows.length / PAGE) - 1)); const view = rows.slice(page * PAGE, (page + 1) * PAGE);
  const th = (id, label, num) => `<th class="sort ${num ? "num" : ""}" data-act="trajSort" data-v="${id}">${label}${S.trajSort === id ? " ▾" : ""}</th>`;
  let h = `<div class="toolbar"><label class="small">outcome <select data-act="trajOutcome"><option value="">all</option>${["PASS", "FAIL", "UNRESOLVED", "UNGRADED"].map(o => `<option ${S.trajOutcome === o ? "selected" : ""}>${o}</option>`).join("")}</select></label><label class="small">task <select data-act="trajTask"><option value="">all</option>${uniq(R.map(r => r.task_id)).sort().map(t => `<option ${S.trajTask === t ? "selected" : ""}>${t}</option>`).join("")}</select></label><span class="small">${rows.length} runs · page ${page + 1}/${Math.max(1, Math.ceil(rows.length / PAGE))}</span>${rows.length > PAGE ? `<button class="btn small sec" data-act="page" data-v="-1">‹</button><button class="btn small sec" data-act="page" data-v="1">›</button>` : ""}<button class="btn small sec" data-act="csv">export CSV</button>${S.multi.size ? `<button class="btn small" data-act="multiOpen">compare ${S.multi.size} selected</button><button class="btn small sec" data-act="multiClear">clear</button>` : ""}</div>`;
  h += `<div class="tbl"><table><tr><th><input type="checkbox" class="check" data-act="multiPage" title="select this page"></th>${th("run", "run")}${th("task", "task")}<th>cell</th>${th("outcome", "outcome")}${th("steps", "steps", 1)}${th("tokens", "tokens", 1)}${th("cost", "cost", 1)}<th>action sequence</th>${th("fails", "predicates that fail")}<th>exit</th></tr>`;
  view.forEach(r => { h += `<tr class="click ${S.sel === r.key ? "selrow" : ""}" data-act="sel" data-key="${esc(r.key)}"><td><input type="checkbox" class="check" data-act="multiToggle" data-key="${esc(r.key)}" ${S.multi.has(r.key) ? "checked" : ""}></td><td class="mono">${esc(runShort(r))}</td><td>${esc(r.task_id)}<div class="small">r${r.repeat_index}</div></td><td class="small">${esc(cellLabel(r))}</td><td>${outBadge(outcome(r, key))}</td><td class="num">${r.steps}</td><td class="num">${ints(tokOf(r))}</td><td class="num">${usd(r.cost_usd)}</td><td>${seqHtml(seqOf(r))}</td><td>${predBadges(r)}</td><td class="small">${esc(r.exit_reason)}</td></tr>`; });
  h += `</table></div><p class="small">Alphabet: L list · R read/view · F search · W write · E edit · T run tests · B bash/other · S submit. Click a row to open it; the checkbox adds it to a multi-run comparison.</p>`;
  return h;
}
function spanHtml(s, hl, prevContent) {
  const cls = { chat: "chat", execute_tool: "tool", edit: "edit", boundary_event: "boundary", grade: "grade", invoke_agent: "invoke" }[s.span] || "";
  let body = "";
  if (s.span === "chat") body = `<div>${esc(s.text) || "<span class='small'>(no text)</span>"}</div>${(s.calls || []).map(c => `<div class="args mono">→ ${esc(c.name)}(${esc(Object.entries(c.args || {}).map(([k, v]) => k + "=" + JSON.stringify(String(v).slice(0, 160))).join(", "))})</div>`).join("")}<div class="small">gen_ai.usage.input_tokens=${s.in} · output_tokens=${s.out} · ${s.ms} ms · ${usd(s.cost)} · finish ${esc((s.finish || []).join(","))}</div>`;
  else if (s.span === "execute_tool") {
    const args = s.args || {}; const argText = Object.entries(args).filter(([k]) => !(s.tool === "write_file" && k === "content") && !(s.tool === "edit_file" && (k === "old" || k === "new"))).map(([k, v]) => k + "=" + JSON.stringify(String(v).slice(0, 200))).join(", ");
    body = `<div class="args mono">${esc(s.tool)}${s.kind ? `<span class="badge info">${esc(s.kind)}</span>` : ""}(${esc(argText)}) <span class="badge ${s.status === "ok" ? "ok" : "bad"}">${esc(s.status)}</span> <span class="small">${s.ms} ms</span></div>`;
    if (s.tool === "edit_file" && args.old != null) body += diffHtml(lineDiff(String(args.old), String(args.new || "")), 1);
    else if (s.tool === "write_file" && args.content != null) body += prevContent != null ? diffHtml(lineDiff(prevContent, String(args.content)), 2) : `<details><summary class="small">new file content (${String(args.content).split("\n").length} lines)</summary><pre>${esc(String(args.content).slice(0, 4000))}</pre></details>`;
    if (s.preview) body += `<pre>${esc(s.preview)}</pre>`;
  }
  else if (s.span === "edit") body = `<div>edited <code>${esc(s.path)}</code> via ${esc(s.tool)}: <span style="color:var(--teal)">+${s.la}</span> / <span style="color:var(--fail)">−${s.lr}</span> lines</div>`;
  else if (s.span === "boundary_event") body = `<div><b>${esc(s.kind)}</b> via ${esc(s.tool)} · <span class="badge ${s.status === "blocked" ? "warn" : "bad"}">${esc(s.status)}</span> <span class="mono">${esc(JSON.stringify(s.args))}</span></div>`;
  else if (s.span === "grade") body = `<div>oracle: visible ${s.visible == null ? "n/a" : s.visible ? "✔" : "✘"} · hidden ${s.hidden == null ? "n/a" : s.hidden ? "✔" : "✘"} · strengthened ${s.strong == null ? "n/a" : s.strong ? "✔" : "✘"} · tests modified ${s.tests_modified ? "yes" : "no"}</div>`;
  else if (s.span === "invoke_agent") body = s.status === "start" ? `<div class="small">run start · harness config recorded in this span</div>` : `<div>run end · exit <b>${esc(s.exit_reason)}</b> · ${ints(s.total_tokens)} tokens · ${usd(s.cost)}</div>`;
  return `<div class="span ${cls} ${hl === s.seq ? "hl" : ""}" id="sp_${s.seq}"><div class="hd"><span class="seq">#${s.seq}</span><span class="kind">${esc(s.span)}${s.span === "chat" && s.step != null ? " · step " + s.step : ""}</span></div>${body}</div>`;
}
function trajViewer() {
  const r = S.sel ? runByKey(S.sel) : null;
  if (!r) return empty("Pick a run from the list or click a cell on the Board.");
  const det = S.detail[r.key]; const spans = spansOf(r); const ps = predicates(spans); const tools = toolSpans(spans); const seq = tools.map(codeOf).join("");
  const curIdx = S.hl != null ? tools.findIndex(s => s.seq === S.hl) : -1;
  const R = listRows(filtered()); const pos = R.findIndex(x => x.key === r.key);
  let h = `<div class="toolbar"><button class="btn small sec" data-act="nav" data-v="-1" ${pos <= 0 ? "disabled" : ""}>‹ previous</button><span class="small">${pos + 1} / ${R.length} in the current list</span><button class="btn small sec" data-act="nav" data-v="1" ${pos >= R.length - 1 ? "disabled" : ""}>next ›</button><button class="btn small sec" data-act="multiToggle" data-key="${esc(r.key)}">${S.multi.has(r.key) ? "remove from selection" : "add to selection"}</button><button class="btn small sec" data-act="trajTab" data-v="compare">compare with another run of ${esc(r.task_id)}</button><button class="btn small sec" data-act="runjson">run JSON</button></div>`;
  h += `<div class="row"><div class="col" style="flex:2 1 560px"><div class="card"><h4>${esc(r.run_id)} <span class="small">${esc(r.results)}</span></h4><div class="kv"><div>cell</div><div><b>${esc(r.model)}</b> × <b>${esc(r.harness_id)}</b> × <b>${esc(r.task_id)}</b> · repeat ${r.repeat_index}</div><div>outcome</div><div>visible ${r.visible_pass == null ? "n/a" : r.visible_pass ? "✔" : "✘"} · hidden ${r.hidden_pass == null ? "n/a" : r.hidden_pass ? "✔" : "✘"} · strengthened ${r.strong_pass == null ? "n/a" : r.strong_pass ? "✔" : "✘"} → under the selected oracle: ${outBadge(outcome(r))}</div><div>exit</div><div>${esc(r.exit_reason)} after ${r.steps} model calls, ${r.tool_calls} tool calls, ${r.edits} edits (${r.lines_added}+/${r.lines_removed}−) in ${(r.files_touched || []).join(", ") || "no files"}</div><div>telemetry</div><div>${ints(r.input_tokens)} in + ${ints(r.output_tokens)} out tokens · ${usd(r.cost_usd)} · ${ints(latencyOf(r))} ms model time${r.boundary_events ? ` · <span class="badge bad">${r.boundary_events} boundary event(s)</span>` : ""}</div><div>sequence</div><div>${seqHtml(seq, curIdx)}</div></div>${svgTokens(spans, { w: 640, h: 130 })}</div>`;
  h += `<div class="card"><h4>Predicates on this trajectory</h4><table class="predicates" style="width:100%"><tr><th>predicate</th><th>formula</th><th>holds</th><th>evidence</th></tr>${ps.map(p => `<tr ${p.at != null ? `class="click" data-act="scroll" data-seq="${p.at}"` : ""}><td>${esc(p.label)}</td><td class="mono">${esc(p.formula)}</td><td>${okBadge(p.ok)}</td><td class="small">${esc(p.note)}${p.at != null ? ` <span class="small">(span #${p.at})</span>` : ""}</td></tr>`).join("")}</table></div>`;
  h += `<div class="card"><h4>Timeline over model and tool time <span class="small">(click a bar to jump)</span></h4>${svgGantt(spans, { w: 640 })}</div>`;
  if (MODE === "server" && !det) h += `<div class="small">Loading the untruncated ledger and the patch…</div>`;
  if (det && det.patch) h += `<div class="card"><h4>patch.diff</h4>${diffHtml(det.patch.split("\n").map(l => [l.startsWith("+") && !l.startsWith("+++") ? "add" : l.startsWith("-") && !l.startsWith("---") ? "del" : "ctx", l]), 99)}</div>`;
  // timeline with diffs against the previous write of the same file
  const lastContent = {}; let tl = "";
  spans.forEach(s => { let prev = null; if (s.span === "execute_tool" && s.tool === "write_file" && s.args && s.args.path) { prev = lastContent[s.args.path] != null ? lastContent[s.args.path] : null; lastContent[s.args.path] = s.args.content; } if (s.span === "execute_tool" && s.tool === "read_file" && s.preview && !/\[\+\d+ chars\]/.test(s.preview)) { const raw = s.preview.replace(/^\s*\d+\| ?/gm, ""); if (s.args && s.args.path && lastContent[s.args.path] == null) lastContent[s.args.path] = raw; } tl += spanHtml(s, S.hl, prev); });
  h += `</div><div class="col" style="flex:3 1 640px"><h4 style="margin:8px 0">Ledger (${spans.length} spans)</h4><div class="timeline">${tl}</div></div></div>`;
  return h;
}
function trajCompare(R) {
  const a = S.sel ? runByKey(S.sel) : null; if (!a) return empty("Select a run first (Run list or Board), then pick a second run of the same task here.");
  const cands = R.filter(r => r.task_id === a.task_id && r.key !== a.key);
  let h = `<div class="card"><b>τ₁</b> = ${esc(a.run_id)} (${esc(cellLabel(a))}, ${outBadge(outcome(a))}) · <b>τ₂</b> = <select data-act="cmp"><option value="">choose a run of ${esc(a.task_id)}</option>${cands.map(r => `<option value="${esc(r.key)}" ${S.cmp === r.key ? "selected" : ""}>${esc(runShort(r))} · ${esc(cellLabel(r))} · ${outcome(r)} · ${r.steps} steps · ${seqOf(r)}</option>`).join("")}</select></div>`;
  const b = S.cmp ? runByKey(S.cmp) : null; if (!b) return h;
  const sa = seqOf(a), sb = seqOf(b), d = levenshtein(sa, sb);
  h += `<div class="tiles">${tile(outcome(a) === outcome(b) ? "O(τ₁) = O(τ₂)" : "O(τ₁) ≠ O(τ₂)", "outcome", `${outcome(a)} vs ${outcome(b)}`)}${tile(d, "edit distance between action sequences", `${sa.length} vs ${sb.length} actions · normalised ${fmt(d / Math.max(sa.length, sb.length), 2)}`)}${tile(ints(tokOf(a)) + " / " + ints(tokOf(b)), "tokens τ₁ / τ₂", `${usd(a.cost_usd)} / ${usd(b.cost_usd)}`)}${tile(commonPrefix([sa, sb]).length, "shared prefix length", "actions identical from the start")}</div>`;
  const pa = predicates(spansOf(a)), pb = predicates(spansOf(b));
  h += `<div class="row"><div class="col"><div class="card"><h4>τ₁ · ${esc(a.run_id)}</h4>${seqHtml(sa)}<table style="width:100%;margin-top:8px">${pa.map(p => `<tr><td>${esc(p.label)}</td><td>${okBadge(p.ok)}</td><td class="small">${esc(p.note)}</td></tr>`).join("")}</table>${svgTokens(spansOf(a), { w: 420, h: 110 })}</div></div>`;
  h += `<div class="col"><div class="card"><h4>τ₂ · ${esc(b.run_id)}</h4>${seqHtml(sb)}<table style="width:100%;margin-top:8px">${pb.map(p => `<tr><td>${esc(p.label)}</td><td>${okBadge(p.ok)}</td><td class="small">${esc(p.note)}</td></tr>`).join("")}</table>${svgTokens(spansOf(b), { w: 420, h: 110 })}</div></div></div>`;
  const diffs = pa.filter((p, i) => p.ok !== pb[i].ok).map(p => p.label);
  h += `<div class="callout ${diffs.length ? "" : "teal"}">${diffs.length ? "Same task, " + (outcome(a) === outcome(b) ? "same outcome, " : "") + "different conduct: " + diffs.join("; ") + ". The outcome-level oracle cannot see this; a trajectory test can." : "Both trajectories satisfy the same predicates. Compare the sequences and the token totals for what still differs."}</div>`;
  // side by side ledgers, chat text only
  const ca = spansOf(a).filter(s => s.span === "chat"), cb = spansOf(b).filter(s => s.span === "chat"); const n = Math.max(ca.length, cb.length);
  h += `<h4 style="margin-top:14px">Model calls side by side</h4><div class="tbl"><table><tr><th>#</th><th>τ₁</th><th>τ₂</th></tr>${Array.from({ length: n }, (_, i) => `<tr><td class="num">${i}</td><td class="small" style="max-width:520px">${ca[i] ? esc(ca[i].text).slice(0, 220) + (ca[i].calls || []).map(c => ` <span class="mono">→ ${esc(c.name)}</span>`).join("") : ""}</td><td class="small" style="max-width:520px">${cb[i] ? esc(cb[i].text).slice(0, 220) + (cb[i].calls || []).map(c => ` <span class="mono">→ ${esc(c.name)}</span>`).join("") : ""}</td></tr>`).join("")}</table></div>`;
  return h;
}
function trajMulti() {
  const runs = Array.from(S.multi).map(runByKey).filter(Boolean); if (runs.length < 2) return empty("Select two or more runs (checkboxes in the run list, shift-click on the Board, or 'add to selection' in the viewer).");
  const key = oracleKey(); const seqs = runs.map(seqOf); const L = Math.max(...seqs.map(s => s.length));
  let h = `<div class="toolbar"><span class="small">${runs.length} runs selected</span><button class="btn small sec" data-act="multiClear">clear</button></div>`;
  h += `<div class="tbl"><table><tr><th></th><th>run</th><th>cell · task</th><th>outcome</th><th class="num">steps</th><th class="num">tokens</th><th class="num">cost</th><th>sequence (aligned left)</th><th>fails</th></tr>`;
  runs.forEach((r, i) => { h += `<tr class="click" data-act="sel" data-key="${esc(r.key)}"><td><button class="btn small sec" data-act="multiToggle" data-key="${esc(r.key)}" title="remove">×</button></td><td class="mono">${esc(runShort(r))}</td><td class="small">${esc(cellLabel(r))} · ${esc(r.task_id)} r${r.repeat_index}</td><td>${outBadge(outcome(r, key))}</td><td class="num">${r.steps}</td><td class="num">${ints(tokOf(r))}</td><td class="num">${usd(r.cost_usd)}</td><td>${seqHtml(seqs[i].padEnd(L, " ").replace(/ /g, "·"))}</td><td>${predBadges(r)}</td></tr>`; });
  h += `</table></div>`;
  const labels = runs.map(runShort); const M = runs.map((_, i) => runs.map((_, j) => levenshtein(seqs[i], seqs[j])));
  h += `<div class="row"><div class="col narrow"><h4>Pairwise edit distance</h4>${heatTable(labels, labels, M, { fmt: v => String(v) })}</div><div class="col"><h4>Predicates across the selection</h4><div class="tbl"><table><tr><th>predicate</th>${runs.map(r => `<th>${esc(runShort(r))}</th>`).join("")}<th class="num">holds</th></tr>${predicates(spansOf(runs[0])).map((p0, pi) => { const vals = runs.map(r => predicates(spansOf(r))[pi].ok); return `<tr><td>${esc(p0.label)}</td>${vals.map(v => `<td>${okBadge(v)}</td>`).join("")}<td class="num">${vals.filter(v => v === true).length}/${vals.filter(v => v !== null).length}</td></tr>`; }).join("")}</table></div></div></div>`;
  return h;
}

// ============================================================ 4. Patterns (sets of trajectories)
function vPatterns() {
  const R = filtered(), key = oracleKey(); if (!R.length) return `<h2>Patterns</h2>` + empty();
  const cells = uniq(R.map(cellOf)); const cell = S.patCell && cells.includes(S.patCell) ? S.patCell : "";
  let rows = cell ? R.filter(r => cellOf(r) === cell) : R; const tasks = uniq(rows.map(r => r.task_id)).sort(); const task = S.patTask && tasks.includes(S.patTask) ? S.patTask : ""; if (task) rows = rows.filter(r => r.task_id === task);
  const g = graded(rows, key); const pass = g.filter(r => r[key]), fail = g.filter(r => !r[key]);
  let h = `<h2>Patterns across trajectories</h2><p class="claim">Sets of runs, not one run: which action follows which, when the first edit happens, where runs of the same task diverge, and which shapes of trajectory fail. Everything is over the action alphabet (L list · R read/view · F search · W write · E edit · T run tests · B bash/other · S submit).</p>`;
  h += `<div class="toolbar"><label class="small">cell <select data-act="patCell"><option value="">all cells in filter</option>${cells.map(c => `<option value="${esc(c)}" ${cell === c ? "selected" : ""}>${esc(c.replace("|", " · "))}</option>`).join("")}</select></label><label class="small">task <select data-act="patTask"><option value="">all tasks</option>${tasks.map(t => `<option ${task === t ? "selected" : ""}>${esc(t)}</option>`).join("")}</select></label><span class="small">${rows.length} runs · ${pass.length} pass · ${fail.length} fail</span></div>`;
  // 1. sequences
  const seqGroups = Array.from(by(g, seqOf).entries()).map(([s, rs]) => ({ s, rs, n: rs.length, p: passRate(rs, key), cost: mean(rs.map(r => r.cost_usd || 0)) })).sort((a, b) => b.n - a.n);
  h += `<h3><span class="n">1</span> Distinct action sequences</h3><div class="row"><div class="col"><div class="tbl"><table><tr><th>sequence</th><th class="num">runs</th><th class="num">pass rate</th><th class="num">Wilson 95%</th><th class="num">mean cost</th><th></th></tr>${seqGroups.slice(0, 25).map(x => { const w = wilson(Math.round(x.p * x.n), x.n); return `<tr><td>${seqHtml(x.s)}</td><td class="num">${x.n}</td><td class="num">${pct(x.p)}</td><td class="num">${ciText(w[0], w[1])}</td><td class="num">${usd(x.cost)}</td><td><button class="btn small sec" data-act="multiSet" data-keys="${esc(x.rs.slice(0, 12).map(r => r.key).join(","))}">select ${Math.min(12, x.n)}</button></td></tr>`; }).join("")}</table></div>${seqGroups.length > 25 ? `<div class="small">${seqGroups.length} distinct sequences; first 25 by count</div>` : ""}</div>`;
  const fe = (rs) => rs.map(r => featOf(r).first_edit_step).filter(x => x >= 0); const ft = (rs) => rs.map(r => { const t = toolSpans(spansOf(r)); const i = t.findIndex(isTestSpan); return i; }).filter(x => x >= 0);
  h += `<div class="col narrow"><h4>When does the first edit happen? (step index)</h4><div class="small">passing runs (n=${pass.length})</div>${svgHist(fe(pass), { lo: 0, hi: Math.max(1, ...fe(g)) + 1, bins: 10, color: "#17A398" })}<div class="small">failing runs (n=${fail.length})</div>${svgHist(fe(fail), { lo: 0, hi: Math.max(1, ...fe(g)) + 1, bins: 10, color: "#E4572E" })}<h4 style="margin-top:10px">When is the first test run?</h4><div class="small">passing</div>${svgHist(ft(pass), { lo: 0, hi: Math.max(1, ...ft(g)) + 1, bins: 10, color: "#17A398" })}<div class="small">failing</div>${svgHist(ft(fail), { lo: 0, hi: Math.max(1, ...ft(g)) + 1, bins: 10, color: "#E4572E" })}</div></div>`;
  // 2. transitions
  const alpha = "LRFWETBS".split("").filter(a => g.some(r => seqOf(r).includes(a)));
  const tp = transitions(pass.map(seqOf)), tf = transitions(fail.map(seqOf));
  const norm = (M) => alpha.map(a => { const tot = sum(alpha.map(b => M[a][b])); return alpha.map(b => tot ? M[a][b] / tot : 0); });
  const Np = norm(tp), Nf = norm(tf); const Nd = Np.map((row, i) => row.map((v, j) => v - Nf[i][j]));
  h += `<h3><span class="n">2</span> What follows what: transition probabilities (row → column)</h3><div class="row"><div class="col narrow"><h4>passing runs</h4>${heatTable(alpha, alpha, Np, { fmt: v => v ? pct(v) : "" })}</div><div class="col narrow"><h4>failing runs</h4>${heatTable(alpha, alpha, Nf, { fmt: v => v ? pct(v) : "" })}</div><div class="col narrow"><h4>difference (pass − fail)</h4>${heatTable(alpha, alpha, Nd, { fmt: v => Math.abs(v) < 0.005 ? "" : (v > 0 ? "+" : "") + pct(v), diverging: true, max: Math.max(0.05, ...Nd.flat().map(Math.abs)) })}<div class="small">teal: more common after passing; orange: more common before failing</div></div></div>`;
  // 3. step-position heatmap
  const K = Math.min(14, Math.max(...g.map(r => seqOf(r).length), 1)); const pos = (rs) => alpha.map(a => Array.from({ length: K }, (_, k) => rs.length ? rs.filter(r => seqOf(r)[k] === a).length / rs.length : 0));
  h += `<h3><span class="n">3</span> What happens at step k: share of runs doing each action at position k</h3><div class="row"><div class="col"><h4>passing</h4>${heatTable(alpha, Array.from({ length: K }, (_, k) => String(k)), pos(pass), { fmt: v => v ? pct(v) : "" })}</div><div class="col"><h4>failing</h4>${heatTable(alpha, Array.from({ length: K }, (_, k) => String(k)), pos(fail), { fmt: v => v ? pct(v) : "" })}</div></div>`;
  // 4. divergence per task
  h += `<h3><span class="n">4</span> Where runs of the same task diverge</h3><div class="tbl"><table><tr><th>task</th><th class="num">runs</th><th>common prefix</th><th>next action → pass rate (n)</th></tr>`;
  uniq(g.map(r => r.task_id)).sort().slice(0, 40).forEach(t => { const rs = g.filter(r => r.task_id === t); if (rs.length < 2) return; const seqs = rs.map(seqOf); const pre = commonPrefix(seqs); const branches = Array.from(by(rs, r => seqOf(r)[pre.length] || "∅").entries()).map(([a, v]) => ({ a, n: v.length, p: passRate(v, key) })).sort((x, y) => y.n - x.n); h += `<tr><td><b>${esc(t)}</b></td><td class="num">${rs.length}</td><td>${pre ? seqHtml(pre) : '<span class="small">none</span>'}</td><td>${branches.map(b => `<span class="cellpick" title="${b.n} runs">${b.a === "∅" ? "end" : seqHtml(b.a)} → ${pct(b.p)} <span class="small">(${b.n})</span></span>`).join(" ")}</td></tr>`; });
  h += `</table></div><p class="small">The prefix is what every run of the task does before the first difference; the branches are the first differing action with the pass rate of the runs that took it. A branch with a low pass rate is a candidate decision to test as a predicate.</p>`;
  // 5. clustering
  const sample = g.slice(0, 250); const k = Math.min(S.patK, sample.length);
  if (sample.length >= 4) { const cl = clusterSequences(sample.map(seqOf), k);
    h += `<h3><span class="n">5</span> Trajectory clusters (average-linkage on edit distance, ${sample.length} runs${g.length > 250 ? " sampled" : ""})</h3><div class="toolbar"><label class="small">clusters <select data-act="patK">${[2, 3, 4, 5, 6, 8].map(x => `<option ${S.patK === x ? "selected" : ""}>${x}</option>`).join("")}</select></label></div><div class="tbl"><table><tr><th>cluster</th><th class="num">runs</th><th>medoid sequence</th><th class="num">pass rate</th><th class="num">mean steps</th><th class="num">mean cost</th><th class="num">mean distance to medoid</th><th></th></tr>${cl.sort((a, b) => b.members.length - a.members.length).map((c, i) => { const rs = c.members.map(j => sample[j]); return `<tr><td><b>${i + 1}</b></td><td class="num">${rs.length}</td><td>${seqHtml(seqOf(sample[c.medoid]))}</td><td class="num">${pct(passRate(rs, key))}</td><td class="num">${fmt(mean(rs.map(r => r.steps)), 1)}</td><td class="num">${usd(mean(rs.map(r => r.cost_usd || 0)))}</td><td class="num">${fmt(mean(c.members.map(j => c.D[c.medoid][j])), 1)}</td><td><button class="btn small sec" data-act="multiSet" data-keys="${esc(rs.slice(0, 12).map(r => r.key).join(","))}">select ${Math.min(12, rs.length)}</button></td></tr>`; }).join("")}</table></div>`; }
  return h;
}

// ============================================================ 5. Queries (trajectory predicates written in the UI)
const QUERY_EXAMPLES = [
  { name: "edit never followed by a test", re: "[WE](?!.*T)", note: "an edit with no run_tests anywhere after it" },
  { name: "submitted without ever testing", re: "^[^T]*S$", note: "the whole run has no T before submit" },
  { name: "bash before reading anything", re: "^[^R]*B", note: "shell before any read/view" },
  { name: "three reads in a row", re: "R{3,}", note: "reading without acting" },
  { name: "test, edit, test (a verify loop)", re: "T[WE]+T", note: "the conduct the prompt asks for" },
  { name: "no submit", re: "^[^S]*$", note: "the harness ended the run" },
];
function queryMatcher(q) {
  let re = null; try { re = q.re ? new RegExp(q.re) : null; } catch (e) { return { error: e.message }; }
  const fn = (r) => { const f = featOf(r); if (re && !re.test(seqOf(r))) return false; if (q.steps_min !== "" && r.steps < Number(q.steps_min)) return false; if (q.steps_max !== "" && r.steps > Number(q.steps_max)) return false; if (q.cost_min !== "" && (r.cost_usd || 0) < Number(q.cost_min)) return false; if (q.exit && r.exit_reason !== q.exit) return false; if (q.boundary === "yes" && !(r.boundary_events > 0)) return false; if (q.boundary === "no" && r.boundary_events > 0) return false; if (q.tests_mod === "yes" && !r.tests_modified) return false; if (q.tests_mod === "no" && r.tests_modified) return false; return true; };
  return { fn };
}
function queryAsTest(q) {
  const cls = (q.name || "query").replace(/[^A-Za-z0-9]+/g, "_").replace(/^_+|_+$/g, "") || "query";
  const conds = [];
  if (q.re) conds.push(`re.search(r${JSON.stringify(q.re)}, t.action_string)`);
  if (q.steps_min !== "") conds.push(`t.summary["steps"] >= ${Number(q.steps_min)}`); if (q.steps_max !== "") conds.push(`t.summary["steps"] <= ${Number(q.steps_max)}`);
  if (q.cost_min !== "") conds.push(`t.summary["cost_usd"] >= ${Number(q.cost_min)}`); if (q.exit) conds.push(`t.summary["exit_reason"] == ${JSON.stringify(q.exit)}`);
  if (q.boundary === "yes") conds.push(`t.summary["boundary_events"] > 0`); if (q.boundary === "no") conds.push(`t.summary["boundary_events"] == 0`);
  if (q.tests_mod === "yes") conds.push(`t.summary["tests_modified"]`); if (q.tests_mod === "no") conds.push(`not t.summary["tests_modified"]`);
  return `# generated by the console from the query "${q.name || q.re}"\nimport os, re, unittest\nfrom harnesslab.core.trajtest import load_runs\n\nclass Test_${cls}(unittest.TestCase):\n    def matches(self, t):\n        return ${conds.join(" and ") || "True"}\n\n    def test_policy_no_run_matches(self):\n        """Gate: fail on any run that matches (use when the pattern is an incident)."""\n        for t in load_runs(os.environ.get("AGENTLAB_RESULTS", "data/runs/live")):\n            with self.subTest(run=t.run_id, seq=t.action_string):\n                self.assertFalse(self.matches(t))\n\n    def test_metric_rate_below_threshold(self):\n        """Metric: the rate of matching runs, with a threshold you set in advance."""\n        runs = load_runs(os.environ.get("AGENTLAB_RESULTS", "data/runs/live"))\n        rate = sum(self.matches(t) for t in runs) / max(1, len(runs))\n        self.assertLessEqual(rate, 0.20, f"{rate:.2f} of {len(runs)} runs match")\n`;
}
function vQueries() {
  const R = filtered(), key = oracleKey(); const q = S.q;
  let h = `<h2>Trajectory queries</h2><p class="claim">Write a predicate over the action string and the run fields, see which runs match, and compare pass rates inside and outside the match. A query that separates failures from successes is a hypothesis; the export turns it into a unittest you can run on any results directory.</p>`;
  h += `<div class="card"><div class="form"><label>name<input data-q="name" value="${esc(q.name)}" placeholder="what the pattern means"></label><label>regex over the action string<input data-q="re" value="${esc(q.re)}" placeholder="e.g. [WE](?!.*T)" class="mono"></label><label>steps ≥<input data-q="steps_min" type="number" value="${esc(q.steps_min)}"></label><label>steps ≤<input data-q="steps_max" type="number" value="${esc(q.steps_max)}"></label><label>cost ≥<input data-q="cost_min" type="number" step="0.001" value="${esc(q.cost_min)}"></label><label>exit reason<select data-q="exit"><option value="">any</option>${uniq(R.map(r => r.exit_reason)).map(e => `<option ${q.exit === e ? "selected" : ""}>${esc(e)}</option>`).join("")}</select></label><label>boundary event<select data-q="boundary"><option value="">any</option><option value="yes" ${q.boundary === "yes" ? "selected" : ""}>yes</option><option value="no" ${q.boundary === "no" ? "selected" : ""}>no</option></select></label><label>tests modified<select data-q="tests_mod"><option value="">any</option><option value="yes" ${q.tests_mod === "yes" ? "selected" : ""}>yes</option><option value="no" ${q.tests_mod === "no" ? "selected" : ""}>no</option></select></label><span><button class="btn" data-act="qsave">save query</button> <button class="btn sec" data-act="qexport">export as unittest</button></span></div>
  <div class="small" style="margin-top:8px">Examples: ${QUERY_EXAMPLES.map(e => `<span class="cellpick" data-act="qex" data-re="${esc(e.re)}" data-name="${esc(e.name)}" title="${esc(e.note)}"><span class="mono">${esc(e.re)}</span> ${esc(e.name)}</span>`).join(" ")}</div></div>`;
  const m = queryMatcher(q); if (m.error) return h + `<div class="callout">regex error: ${esc(m.error)}</div>`;
  const st = predicateStats(R, m.fn, key); const rrTxt = Number.isFinite(st.rr.rr) ? `${fmt(st.rr.rr, 2)} ${Number.isFinite(st.rr.lo) ? ciText(st.rr.lo, st.rr.hi) : ""}` : "n/a";
  const active = q.re || q.steps_min !== "" || q.steps_max !== "" || q.cost_min !== "" || q.exit || q.boundary || q.tests_mod;
  if (active) {
    h += `<div class="tiles">${tile(`${st.matches.length} / ${st.n}`, "runs matching", pct(st.matches.length / (st.n || 1)) + " of graded runs")}${tile(pct(st.passIn), "pass rate inside the match", `${st.b} pass · ${st.a} fail`)}${tile(pct(st.passOut), "pass rate outside", `${st.d} pass · ${st.c} fail`)}${tile(fmt(st.ochiai, 3), "Ochiai (as a failure feature)", "e_f / √(F·(e_f+e_p))")}${tile(rrTxt, "risk ratio of failing, matched vs not", "with 95% interval")}</div>`;
    h += `<div class="callout ${Number.isFinite(st.rr.lo) && st.rr.lo > 1 ? "" : "teal"}">${Number.isFinite(st.rr.lo) && st.rr.lo > 1 ? "Runs that match fail more often, and the interval excludes 1. That is a hypothesis about conduct worth a controlled comparison, not yet a cause." : (Number.isFinite(st.rr.hi) && st.rr.hi < 1 ? "Runs that match fail less often; the pattern looks like conduct that helps." : "No separation the interval can support at this n.")}</div>`;
    h += `<div class="toolbar"><span class="small">${Math.min(60, st.matches.length)} of ${st.matches.length} matches</span>${st.matches.length ? `<button class="btn small sec" data-act="multiSet" data-keys="${esc(st.matches.slice(0, 12).map(r => r.key).join(","))}">compare first 12</button>` : ""}</div><div class="tbl"><table><tr><th>run</th><th>task</th><th>cell</th><th>outcome</th><th class="num">steps</th><th class="num">cost</th><th>sequence</th><th>exit</th></tr>${st.matches.slice(0, 60).map(r => `<tr class="click" data-act="sel" data-key="${esc(r.key)}"><td class="mono">${esc(runShort(r))}</td><td>${esc(r.task_id)}</td><td class="small">${esc(cellLabel(r))}</td><td>${outBadge(outcome(r, key))}</td><td class="num">${r.steps}</td><td class="num">${usd(r.cost_usd)}</td><td>${seqHtml(seqOf(r))}</td><td class="small">${esc(r.exit_reason)}</td></tr>`).join("")}</table></div>`;
  } else h += `<p class="small">Type a regex or a field filter above, or click an example.</p>`;
  if (S.qOpen) h += `<div class="card"><h4>Generated trajectory test <button class="btn small sec" data-act="qclose">close</button></h4><pre style="white-space:pre-wrap;background:var(--code);color:var(--codeink);padding:8px;border-radius:4px;font-size:11.5px">${esc(S.qOpen)}</pre><p class="small">Save as trajectory_tests/test_query.py and run <code>AGENTLAB_RESULTS=data/runs/live python -m unittest trajectory_tests/test_query.py</code>. Decide which of the two methods is your test: the gate or the rate.</p></div>`;
  if (S.qSaved.length) { h += `<h3><span class="n">★</span> Saved queries (this browser)</h3><div class="tbl"><table><tr><th>name</th><th>regex</th><th class="num">matches</th><th class="num">pass in</th><th class="num">pass out</th><th class="num">Ochiai</th><th class="num">risk ratio</th><th></th></tr>${S.qSaved.map((sq, i) => { const mm = queryMatcher(sq); const s2 = mm.fn ? predicateStats(R, mm.fn, key) : null; return `<tr><td><b>${esc(sq.name || "(unnamed)")}</b></td><td class="mono">${esc(sq.re)}</td><td class="num">${s2 ? s2.matches.length : "?"}</td><td class="num">${s2 ? pct(s2.passIn) : ""}</td><td class="num">${s2 ? pct(s2.passOut) : ""}</td><td class="num">${s2 ? fmt(s2.ochiai, 3) : ""}</td><td class="num">${s2 && Number.isFinite(s2.rr.rr) ? fmt(s2.rr.rr, 2) : ""}</td><td><button class="btn small sec" data-act="qload" data-i="${i}">load</button> <button class="btn small sec" data-act="qdel" data-i="${i}">delete</button></td></tr>`; }).join("")}</table></div>`; }
  return h;
}
